name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - name: Install TeX Live packages
      run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-xetex texlive-lang-chinese fonts-noto-cjk
    - name: Build pdf with XeLaTeX
      run: make kactl
    - name: Run compiles
      run: make test-compiles
    - name: Run stress tests
      run: make test
